### ISSUE TITLE
Problem with authentication tab

### ISSUE THREAD

**Issue by tomekwi** [Schnouki/git-annex-remote-hubic#3] opened 2015-03-18 23:30 UTC
Hi, this is the first time I'm using git-annex with a remote, so I might be doing something wrong.

After running `git annex initremote ...` as the readme says I get the following output:
```
An authentication tab should open in your browser. If it does not,
please go to the following URL:
https://api.hubic.com/oauth/auth?...
git-annex: external special remote protocol error, unexpectedly received "Created new window in existing browser session." (unable to parse command)
```

After the `git-annex: ...` error the process exits immediately. But after completing authentication more output comes:
```
<prompt> $ [hubic] git-annex has stopped, exiting.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

I'm running Ubuntu 14.04 with Chromium v40 set up as the default browser.

**Comment by tomekwi** [comment] 2015-03-18 23:41
For the record – everything went smoothly in Firefox, though one suspicious message did show up in the terminal:
```
(process:12283): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
```

**Comment by parhuzamos** [comment] 2015-03-19 09:57
It's because the standard output of the browser is processed. If you have a browser running already (as in this case), you receive the message as above. Normally, no message is written, that is why Firefox works. 

To come around the issue: 
- close all browser windows (ctrl+shift+q)
Or
- replace the default browser while you're doing the initremote (to Firefox) 

To fix the issue: 
The best solution would be to skip all lines of the browser output and take only which begins with http(s)

Hope this helps!

**Comment by vanicat** [comment] 2015-03-19 10:17
Another solution would be to redirect the output of the browser to /dev/null

**Comment by tomekwi** [comment] 2015-03-23 08:16
> close all browser windows (ctrl+shift+q)

This produces exactly the same behaviour.

> replace the default browser while you're doing the initremote (to Firefox)

Yup, that works. But only if Firefox is already running. If it has to be started before opening a new tab, the following happens:

```
<prompt> $ git annex initremote hubic type=external externaltype=hubic encryption=shared hubic_container=annex embedcreds=no --fast
initremote hubic (encryption setup) (shared cipher) (gpg) 
An authentication tab should open in your browser. If it does not,
please go to the following URL:
https://api.hubic.com/oauth/auth?client_id=api_hubic_tddVaawJWrZZoQCTNw9psZHociZx1bcw&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A18181%2F&scope=credentials.r

(process:17143): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(firefox:17143): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(firefox:17143): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(firefox:17143): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(firefox:17143): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised
git-annex: external special remote protocol error, unexpectedly received "WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts)." (unable to parse command)


<prompt> $ [hubic] git-annex has stopped, exiting.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by parhuzamos** [comment] 2015-03-25 17:52
It turns out: I was wrong about standard out.
You just have to make sure, the browser **does not output anything(!)**.

You could try this (it's just a idea, I haven't tried):
- find the default browser's location
```
$ sudo update-alternatives --config x-www-browser
```
- replace that file eg. `/usr/bin/google-chrome-stable` with a symlink to `~/mybrowser.sh`
- `~/mybrowser.sh` could look like this:
```
#!/bin/bash
/usr/bin/google-chrome-stable "$1" &>/dev/null
```
This redirects everything to devnull.
- when starting the `initremote` it will launch `mybrowser.sh` and the authentication sould succeed.

To build the ultimate death-star create two scripts the does the symlink creation and original browser restoration.

**Comment by vanicat** [comment] 2015-03-25 20:46
Reading the code of webbroswser.py, it seem that the problem is that webbrowser run xdg-open or gvfs-open that will run chromium, and don't know that it will be running chromium, and as such decide to not redirect stdin or stdout. It seem that if you ran

         BROWSER=chromium git annex enableremote myremote

then webbroser.py will redirect chromium outpout automatically to /dev/null. I didn't test it, but it realy look like it. So this is probably a simpler solution

**Comment by tomekwi** [comment] 2015-03-25 21:09
Thanks for these great workarounds. Switching temporarily to FF works alright for me.

It's just that I was hoping @Schnouki or a contributor would like to solve it at app level. Perhaps it really is as easy as redirecting stdout as @parhuzamos says?

I'll be glad to help.

**Comment by vanicat** [comment] 2015-03-25 21:23
IMHO, this look like a bug in the webbroser.py python library. It is this module that should know better and redirect stdin and stdout of `xdg-open` (or gvfs-open) to `/dev/null` when running them. The API of this library do not let us easily change the way the redirect is handled. That said, webbroser.api have to take care of a lot of possibility, so may be this is more complex than just that, and I don't have the time and courage to investigate this further.

**Comment by tomekwi** [comment] 2015-03-25 21:30
Seems reasonable, that webbrowser is the culprit. How about a dead simple solution – a flag to display the URL without opening any browser? That could also help with browserless server setups.

**Comment by Schnouki** [comment] 2015-03-26 11:20
Hi all, and sorry for the delayed answer.

Indeed the problem is the `webbrowser` module, which starts processes without redirecting their standard output/error to `/dev/null`. Therefore their stdout is the same as the one of the `git-annex-remote-hubic` process, which is read by git-annex. So when a browser outputs something, git-annex reads it but can't parse it, hence the "protocol error" message.

This problem is known ([issue 22277](http://bugs.python.org/issue22277) on the Python bugtracker), but it won't be fixed until at least Python 3.5.

However I found a nice and simple workaround, which is to call `webbrowser.open_new_tab()` from another process that redirects its output to `/dev/null`, and it's really easy to do with the `multiprocessing` module. I'll push that soon, please tell me if it works!

**Comment by tomekwi** [comment] 2015-03-26 11:52
Thanks a lot for tackling this problem @Schnouki. It looks like the perfect solution until Python itself fixes the issue.

But somehow I keep getting exactly the same error. Maybe I've done the setup wrongly? I didn't uninstall the previous version, but done the following:
```sh
$ git remote update && git checkout devel  # Fresh, up-to-date checkout
$ python3 setup.py install --user  # For some reason the first time always produces errors
$ python3 setup.py install --user  # but it goes smoothly the second time.
```

I've no idea how to test if the updated binary gets executed.

**Comment by Schnouki** [comment] 2015-03-26 13:50
Dammit, you're right! I did something wrong in my tests, so it seemed to work even though it actually doesn't work...
So I now have a hackier solution, which is to temporarily monkey-patch `subprocess.Popen` (which is used by webbrowser) to force its `stdout` and `stderr` arguments to point to `/dev/null`...

**Comment by tomekwi** [comment] 2015-03-26 14:01
Now it works like a charm! Thanks again :beers: :)

**Comment by Schnouki** [comment] 2015-03-26 14:06
Great! I'll release that as v0.3.1 when I have some feedback from @vanicat and @parhuzamos then :)

**Comment by parhuzamos** [comment] 2015-03-26 14:21
+1
Work like a charm!

**Closed** 2015-04-29 09:15 UTC
Labels: bug
